spring:
  datasource:
    name: datasource
    initialize: false
    url: jdbc:mysql://localhost/appinfo
    driver-class-name: com.mysql.jdbc.Driver
    username: test
    password: test
    dbcp2:
      initial-size: 2
      max-idle: 2
      min-idle: 2
      test-on-borrow: true
      max-wait-millis: 10000
    tomcat:
      max-active: 2
  jpa:
    generate-ddl: false
    show-sql: true
