spring:
  datasource:
    name: datasource
    initialize: false
    url: jdbc:mysql://localhost/appinfo?useUnicode=true&amp;characterEncoding=utf8mb4
    driver-class-name: com.mysql.jdbc.Driver
    username: test
    password: test
    dbcp2:
      initial-size: 2
      max-idle: 2
      min-idle: 2
      test-on-borrow: true
      max-wait-millis: 10000
    tomcat:
      max-active: 2
spring.jpa.hibernate.ddl-auto: update



